name: Run tests for posmulten

on:
  push:

jobs:
  compilation_and_unit_tests:
    runs-on: ubuntu-latest
    name: "Compilation and unit tests"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests --quiet && ./mvnw test
  database_tests:
    runs-on: ubuntu-latest
    name: "Database creation tests for multiple postgres versions 9.6, 10, 11, 12, 13"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install bats
        run: .travis/bats/bats-core-installation.sh "$GITHUB_WORKSPACE/.travis/bats"
      - name: Run bats tests
        run: export PATH="$GITHUB_WORKSPACE/.travis/bats/bats-core/bin:$PATH" && bats/run_bats_test_for_all_db_version.sh
  testing_configuration_jar:
    runs-on: ubuntu-latest
    name: "Testing configuration jar"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install bats
        run: .travis/bats/bats-core-installation.sh "$GITHUB_WORKSPACE/.travis/bats"
      - name: Install other libs
        run:  sudo apt-get -y install libxml2-utils
      - name: Run bats tests
        run:  ./mvnw -DskipTests --quiet clean install && export PATH="$GITHUB_WORKSPACE/.travis/bats/bats-core/bin:$PATH" && bats -tr bats/configuration-jar
  integraion_tests:
    runs-on: ubuntu-latest
    name: "Integration and functional tests in postgresql-core module"
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install library for postgres
        run: sudo apt-get install libpq-dev

      - name: Create database
        run: psql -f 'db_scripts/prepare_postgresql-core_db.sql' -U postgres

      - name: Run tests
        run: ./mvnw -DskipTests --quiet clean install && ./mvnw -pl :postgresql-core -P !unit-tests,integration-tests test && ./mvnw -pl :postgresql-core-functional-tests -P !unit-tests,functional-tests test
#  build:
#    runs-on: ubuntu-latest
#    # Service containers to run with `container-job`
#    services:
#      postgres:
#        image: postgres:9.6
#        env:
#          POSTGRES_DB: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_USER: postgres
#        ports:
#          - 5432:5432
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#    #https://awesomeopensource.com/project/Harmon758/postgresql-action
#    steps:
#
#    - name: Git checkout
#      uses: actions/checkout@v2
#
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#
#    - name: Build with Maven
#      run: ./mvnw clean install -DskipTests --quiet && ./mvnw test