name: Run tests for posmulten-hibernate4-spring-boot

on:
  push:

jobs:
  compilation_and_unit_tests:
    runs-on: ubuntu-latest
    name: "Compilation and unit tests"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests --quiet && ./mvnw test

#  build:
#    runs-on: ubuntu-latest
#    # Service containers to run with `container-job`
#    services:
#      postgres:
#        image: postgres:9.6
#        env:
#          POSTGRES_DB: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_USER: postgres
#        ports:
#          - 5432:5432
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#    #https://awesomeopensource.com/project/Harmon758/postgresql-action
#    steps:
#
#    - name: Git checkout
#      uses: actions/checkout@v2
#
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#
#    - name: Build with Maven
#      run: ./mvnw clean install -DskipTests --quiet && ./mvnw test